# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9e56b0cd2a15086f47f8df198813ac588cb24b2c52bfe5956c173c18bdf49b37bc1c79d9020ea18ce839c78a2623e9cda611fa76b9a4318577a73e458dcd7a8a

test:
  secret_key_base: 30a789fa5d6e77e555ff011a28e62534a5d653557968cb7088d5bd579edc4df7068172013e7553867693815b9346a442e8d8bebe92dc84370c5543e48b2bb772

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
